# Generated by Django 3.1.7 on 2021-04-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_competences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
