# Generated by Django 3.1.7 on 2021-04-12 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_competences', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Adresse mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_collaborater',
            field=models.BooleanField(default=False, verbose_name='Collaborateur ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Equipe ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superuser ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name=' Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_competences.society', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom / Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_competences.listworkstation', verbose_name='Poste'),
        ),
    ]
