# Generated by Django 3.1.7 on 2021-04-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_competences', '0004_auto_20210412_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Domaine',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nom d'utilisateur"),
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('commentary', models.CharField(max_length=250, verbose_name='commentaire')),
                ('field', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_competences.field')),
            ],
            options={
                'verbose_name': 'Compétence',
            },
        ),
    ]
